### ISSUE TITLE
Drop-down icon on top right corner not showing

### ISSUE THREAD

**Issue by cuynu** [NeonOrbit/ChatHeadEnabler#9]
Messenger changed new UI interface on version 381.0.0.17.102 and drop-down icon not showing after update to this version

![orca-image--771317952](https://user-images.githubusercontent.com/90895715/194107589-0743fdf6-6d6b-42ee-8a4f-c597718da87c.jpeg)

**Comment by NeonOrbit** [comment]
~~If you need it urgently (assuming your phone is rooted),  go to /data/data/com.facebook.orca/shared_prefs/ and open app.neonorbit.chatheadenabler.pref.xml file. Change "bubble" entry from "false" to "true" and restart messenger.~~

**Comment by NeonOrbit** [comment]
Fixed in version [v2.4.3](https://github.com/NeonOrbit/ChatHeadEnabler/releases/tag/v2.4.3)

**Comment by cuynu** [comment]
> Fixed in version [v2.4.3](https://github.com/NeonOrbit/ChatHeadEnabler/releases/tag/v2.4.3)

Not fixed, problem still persists

**Comment by NeonOrbit** [comment]
> Not fixed, problem still persists

It's working now, tested on new UI too. Please install v2.4.3. 
In order to make sure the module is actually loading, disable it and enable again from LSPosed manager. 
Clear messenger app data, just in case. 

It should work after that. If the problem still persists, please send LSPosed log.
**Please let us know if it's working.**

<picture><img src="https://user-images.githubusercontent.com/66206913/196735211-b7454b74-c9bb-429c-964e-384436394b19.jpg" width=400/></picture>

**Comment by NeonOrbit** [comment]
@cuynu  Please let us know if it's working. (first follow the procedures in last comment.)

**Comment by cuynu** [comment]
Not working at all

**Comment by cuynu** [comment]
Followed all

**Comment by NeonOrbit** [comment]
Please send LSPosed log

**Comment by cuynu** [comment]
[LSPosed_2022-10-20T00_09_07.601.zip](https://github.com/NeonOrbit/ChatHeadEnabler/files/9822712/LSPosed_2022-10-20T00_09_07.601.zip)

**Comment by NeonOrbit** [comment]
Try this one, and send log again. (Not need to clear data, just force close messenger)
[ChatHeadEnabler-v2.4.3-dev3.zip](https://github.com/NeonOrbit/ChatHeadEnabler/files/9823057/ChatHeadEnabler-v2.4.3-dev3.zip)
